
name: gym_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  
  # Cliente para consumir los endpoints de spring boot
  http: ^1.6.0
  
  # Paquete para generar la vista del codigo qr
  qr_flutter: ^4.1.0
  
  # Paquete para usar la camara del dispositivo como escaner
  mobile_scanner: ^7.2.0
  
  # Paquete para manejo de fechas y formatos
  intl: ^0.20.2
  
  cupertino_icons: ^1.0.8
  fl_chart: ^1.2.0
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  
  # CORRECCIÓN: Versión estable compatible con el código actual
  google_sign_in: 6.2.1
  image_picker: ^1.2.2
  supabase_flutter: ^2.12.4
  shared_preferences: ^2.5.5
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true