// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrZNjh1iLPajpRJnCX_7yIIq4QkRv_mjQ',
    appId: '1:71338526773:web:818e5260fca5680f71497c',
    messagingSenderId: '71338526773',
    projectId: 'gym-app-e3f03',
    authDomain: 'gym-app-e3f03.firebaseapp.com',
    storageBucket: 'gym-app-e3f03.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJIDFbeZo_30JS3uEgb3LOAxI2olBjVrs',
    appId: '1:71338526773:android:dc38e12b5d42ca8b71497c',
    messagingSenderId: '71338526773',
    projectId: 'gym-app-e3f03',
    storageBucket: 'gym-app-e3f03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1hsaxrzxuZF_tVF80Tn9lz-yY0pqpzCY',
    appId: '1:71338526773:ios:741887f2ddc1f11d71497c',
    messagingSenderId: '71338526773',
    projectId: 'gym-app-e3f03',
    storageBucket: 'gym-app-e3f03.firebasestorage.app',
    iosClientId: '71338526773-6ghi8bq98eostvpd5vfuac73d3rueh74.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1hsaxrzxuZF_tVF80Tn9lz-yY0pqpzCY',
    appId: '1:71338526773:ios:741887f2ddc1f11d71497c',
    messagingSenderId: '71338526773',
    projectId: 'gym-app-e3f03',
    storageBucket: 'gym-app-e3f03.firebasestorage.app',
    iosClientId: '71338526773-6ghi8bq98eostvpd5vfuac73d3rueh74.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrZNjh1iLPajpRJnCX_7yIIq4QkRv_mjQ',
    appId: '1:71338526773:web:50eb7b2cc803801f71497c',
    messagingSenderId: '71338526773',
    projectId: 'gym-app-e3f03',
    authDomain: 'gym-app-e3f03.firebaseapp.com',
    storageBucket: 'gym-app-e3f03.firebasestorage.app',
  );
}
